#!/bin/bash

# Ensure that a parameter is passed
if [ $# -eq 0 ]; then
    echo "Usage: comm <string to pass>"
    exit 1
fi

# Combine all parameters into a single string
PARAM="$*"
echo $PARAM

# Execute the commands
git stage -A
git commit -m "$PARAM"
git push
